const INDEXOFGOLD = 1;
const INDEXOFEXPERIENCE = 2;
const INDEXOFENERGY = 0;
const INDEXOFJADE = 5;
const INDEXOFGARNET = 6;
const INDEXOFOBSID = 7;
const INDEXOFMOON = 8;
const INDEXOFAMBER = 9;
const AWARDABLEARENAINDEXSTART = INDEXOFJADE;
const AWARDABLEARENAINDEXEND = INDEXOFAMBER;

export {
  INDEXOFGOLD,
  INDEXOFEXPERIENCE,
  INDEXOFENERGY,
  INDEXOFJADE,
  AWARDABLEARENAINDEXSTART,
  AWARDABLEARENAINDEXEND,
};
