const INDEXOFGOLD = 1;
const INDEXOFEXPERIENCE = 2;
const INDEXOFENERGY = 0;
const INDEXOFTOKEN1 = 3;
const INDEXOFTOKEN2 = 4;
const INDEXOFJADE = 5;
const INDEXOFGARNET = 6;
const INDEXOFOBSID = 7;
const INDEXOFMOON = 8;
const INDEXOFAMBER = 9;
const AWARDABLEARENAINDEXSTART = INDEXOFJADE;
const AWARDABLEARENAINDEXEND = INDEXOFAMBER;

const NAMEOFGOLD = "gold";
const NAMEOFTOKEN1 = "blackstone";
const NAMEOFTOKEN2 = "whitestone";

const ARENAEVENTINTERVAL = 60000000;
const LIVESINTERVAL = 300000;

export {
  INDEXOFGOLD,
  INDEXOFEXPERIENCE,
  INDEXOFENERGY,
  INDEXOFJADE,
  AWARDABLEARENAINDEXSTART,
  AWARDABLEARENAINDEXEND,
  INDEXOFTOKEN1,
  INDEXOFTOKEN2,
  NAMEOFGOLD,
  NAMEOFTOKEN1,
  NAMEOFTOKEN2,
  ARENAEVENTINTERVAL,
  LIVESINTERVAL,
};
