name: Code Climate
on:
  push:
jobs:
  build:
    name: Test Coverage
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: some
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install packages frontend
        run: npm install

      - name: Run tests and build a report
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          npm run coverage
          ./cc-test-reporter format-coverage -t lcov -o cc.coverage ./coverage/lcov.info
          ./cc-test-reporter -i cc.coverage upload-coverage
